/* THIS FILE IS GENERATED DO NOT EDIT */
#ifndef DONORS_GEN_H
#define DONORS_GEN_H
const char *const DONORS_PATRONS[] = {
	"OSS Capital <https://oss.capital>",
	"Re-Logic <https://re-logic.com>",
	0
};
const char *const DONORS_SPONSORS_PLATINUM[] = {
	"Heroic Labs <https://heroiclabs.com>",
	"Ramatak <https://ramatak.com>",
	"V-Sekai <https://github.com/V-Sekai>",
	"W4 Games <https://w4games.com>",
	0
};
const char *const DONORS_SPONSORS_GOLD[] = {
	"Mega Crit <https://www.megacrit.com>",
	"Prehensile Tales <https://prehensile-tales.com>",
	"Robot Gentleman <http://robotgentleman.com>",
	0
};
const char *const DONORS_SPONSORS_SILVER[] = {
	"Affray Interactive <https://scp.games/pandemic>",
	"Broken Rules <https://brokenrul.es>",
	"Chasing Carrots <https://www.chasing-carrots.com>",
	"Delton Ding",
	"Gamblify <https://www.gamblify.com>",
	"Null <https://null.com>",
	"Orbital Knight <https://www.orbitalknight.com>",
	"Playful Studios <https://playfulstudios.com>",
	0
};
const char *const DONORS_MEMBERS_DIAMOND[] = {
	"Sealow",
	"Sylv <https://rankith.itch.io/unnamed-space-idle-prototype>",
	"And 5 anonymous donors",
	0
};
const char *const DONORS_MEMBERS_TITANIUM[] = {
	"Basically Games",
	"FDG Entertainment <https://www.fdg-entertainment.com/>",
	"Game Dev Artisan <https://gamedevartisan.com/>",
	"Garry Newman",
	"Isaiah Smith <https://www.isaiahsmith.dev/>",
	"katnamag <https://katnamag.com/>",
	"Kenney <https://kenney.nl/>",
	"Lucid Silence Games",
	"Matthew Campbell",
	"Maxim Karsten",
	"Midjiwan AB <https://polytopia.io/>",
	"PolyMars <https://polymars.dev/>",
	"Razenpok <https://www.youtube.com/watch?v=-QxI-RP6-HM>",
	"RPG in a Box <https://www.rpginabox.com/>",
	"Sterling Long <https://www.sterlinglong.me/>",
	"Sunshower <https://github.com/Phanterm>",
	"TrampolineTales <https://trampolinetales.com/>",
	"Wilfred James <https://twitter.com/0430agi>",
	"And 8 anonymous donors",
	0
};
const char *const DONORS_MEMBERS_PLATINUM[] = {
	"AD Ford",
	"Andy Touch",
	"BlockImperiumGames (BIG)",
	"Christian Baune",
	"Christoph Woinke",
	"Christopher Shifflett",
	"Darrin Massena",
	"Druvsaft",
	"Edward Flick",
	"F*ckedByUnity",
	"Golden Skull Art",
	"HP van Braam",
	"Jonah Stich",
	"Justin McGettigan",
	"Justo Delgado Baud\303\255",
	"Marek Belski",
	"Matthew Ekenstedt",
	"Mike King",
	"Nassor Paulino da Silva",
	"Neal Gompa (Conan Kudo)",
	"Ronnie Cheng",
	"Ryan Heath",
	"Samantha",
	"Scott Pezza",
	"ShikadiGum",
	"Silver Creek Entertainment",
	"Stephan Kessler",
	"Stephan Lanfermann",
	"TigerJ",
	"Tim Yuen",
	"Violin Iliev",
	"Vladim\303\255r Chv\303\241til",
	"iCommitGames",
	"nate-wilkins",
	"And 18 anonymous donors",
	0
};
const char *const DONORS_MEMBERS_GOLD[] = {
	"@reilaos",
	"Antti Vesanen",
	"Artur Ilkaev",
	"Asher Glick",
	"Ashtreighlia",
	"Atsui",
	"Ben Burbank",
	"Ben Rog-Wilhelm",
	"Benito",
	"Benjamin Sarsgard",
	"Benjo Kho",
	"Bernd Barsuhn",
	"Blake Farnsworth",
	"Brian Ernst",
	"Brian Levinsen",
	"Brut",
	"Chen-Pang He (jdh8)",
	"ClarkThyLord",
	"Cosmin Munteanu",
	"Coy Humphrey",
	"Daniel James",
	"David Chen Zhen",
	"David Coles",
	"David Hubber",
	"David Snopek",
	"Dehyvis Coronel",
	"Dustuu",
	"Ed Morley",
	"ElektroFox",
	"Enclusa Games",
	"Ends",
	"Eric Phy",
	"Faisal Al-Kubaisi (QatariGameDev)",
	"FeralBytes",
	"Frederick Ayala",
	"GlassBrick",
	"Grau",
	"Guangzhou Lingchan",
	"HTML5onMobilePLZ",
	"Hammster",
	"Hendrik Mans",
	"Here's my 20 cents",
	"Iggy Zuk",
	"Illyan",
	"Jacob (HACKhalo2 Studios)",
	"Jam",
	"James Green",
	"Jason Cawood",
	"Javier Roman",
	"Joel Martinez",
	"John Gabriel",
	"Jon Woodward",
	"Jos\303\251 Canepa",
	"Jo\303\243o Pedro Braz",
	"KAR Games",
	"Kamran Wali",
	"Karasu Studio",
	"KekLuck",
	"Kenneth Christensen",
	"Kristian Kriehl",
	"Logan Apple",
	"Luca Junge",
	"Luca Vazzano",
	"LyaaaaaGames",
	"MHDante",
	"Malcolm Nixon",
	"Manuel Requena",
	"Mark Schramm",
	"Martin Agnar Dahl",
	"Martin \305\240enke\305\231\303\255k",
	"Matheus Gritz",
	"Megabit Interactive",
	"Mennskr",
	"Metanaut",
	"Modus Ponens",
	"Niklas Wahrman",
	"NotNet",
	"Obelisk Island Studios",
	"Officine Pixel S.n.c.",
	"Oleksii Nosov",
	"Pav Soor",
	"Piotr Siuszko",
	"RAWRLAB Games",
	"RadenTheFolf",
	"Request",
	"Robin Ward",
	"Saltlight Studio",
	"Samuel Judd",
	"Silverclad Studios",
	"Sofox",
	"Space Kraken Studios",
	"Spoony Panda",
	"Sympa City",
	"ThePolyglotProgrammer",
	"Tim Nedvyga",
	"Tom Langwaldt",
	"Trevor Slocum",
	"Vincent Foulon",
	"Weasel Games",
	"WuotanStudios.com",
	"Zi",
	"albinaask",
	"endaye",
	"getIntoGameDev",
	"hiulit",
	"korinVR",
	"nezticle",
	"ohanaya3",
	"re:thinc",
	"tukon",
	"zikes",
	"\346\235\250\347\203\210\350\203\234(zedrun)",
	"Alexander Erlemann",
	"Alexandre VALIN",
	"Alex Khayrullin",
	"Algebrute",
	"Andriy",
	"Antanas Paskauskas",
	"anti666",
	"Ari",
	"Arisaka Mayuki",
	"Arthur S. Muszynski",
	"Bread",
	"Cameron Connolly",
	"Charlie Whitfield",
	"Craig Ostrin",
	"Craig Swain",
	"CzechBlueBear",
	"Daniel Eichler",
	"Daniel Reed",
	"Dennis Belfrage",
	"Emily A. Bellows",
	"Eric Brand",
	"Felix Winterhalter",
	"Fransiska",
	"George Venizelos",
	"Harry Tumber",
	"Harvey Fong",
	"Horv\303\241th-L\303\241z\303\241r P\303\251ter",
	"illuxxium",
	"James Couzens",
	"Jared White",
	"Jes\303\272s Chicharro",
	"Joel Fivat",
	"Johnathan Kupferer",
	"Josef Stumpfegger",
	"Josh Nygaard",
	"Joshua Lesperance",
	"Kelteseth",
	"Khora",
	"kickmaniac",
	"Liam Smyth",
	"LoparPanda",
	"Marcus Dobler",
	"Martin Gulliksson",
	"Martin Soucek",
	"Matt Greene",
	"Matthew Dana",
	"Michael D\303\274rwald",
	"Michael Policastro",
	"n00sh",
	"nate etan",
	"Nicol\303\241s Monner Sans",
	"Nikita Rotskov",
	"Nikola Whallon",
	"Oliver Dick",
	"Patrick Wuttke",
	"Pete Goodwin",
	"Philip Woods",
	"Reilt",
	"Rickard Hermanson",
	"Rob",
	"Rob McInroy",
	"RodZilla",
	"Ronnie Ashlock",
	"Ruzgud",
	"Ryan Breaker",
	"\042Sage Automatic Systems, LLC\042",
	"Shishir Tandale",
	"Song Junwoo",
	"spacechase0",
	"sus",
	"Talii",
	"Thomas Kurz",
	"Tobias Bocanegra",
	"Tobias Raggl",
	"Torbulous",
	"toto bibi",
	"Valryia",
	"VoidPointer",
	"whatever",
	"Yifan Lai",
	"zkip lan",
	"Aaron Mayfield",
	"Adam Carr",
	"Adam Smeltzer",
	"Adisibio",
	"Adrien de Pierres",
	"Agustinus Arya",
	"Aidan Marwick",
	"Aidan O'Flannagain",
	"aiekick",
	"Aiguo Wang",
	"AJWolbers",
	"Aki Mimoto",
	"Alan Beauchamp",
	"Alder Stefano",
	"Alejandro Saucedo",
	"AleMax",
	"Alex Clavelle",
	"Alex de la Mare",
	"alex raeside",
	"Andre Altmueller",
	"Andreas \303\230stergaard Nielsen",
	"Andrei Pufu",
	"Andre Stackhouse",
	"Andrew",
	"Andrew Groot",
	"andrew james morris",
	"Ano Nim",
	"Arch Toasty",
	"Arda Erol",
	"Arthur Brainville",
	"Arturo Rosales",
	"Ash K",
	"Aubrey Falconer",
	"Austin Miller",
	"Azar Gurbanov",
	"AzulCrescent",
	"Bal\303\241zs Bat\303\241ri",
	"Beau Seymour",
	"Benedikt",
	"Ben Visness",
	"Bill Thibault",
	"Bjarne Voigtl\303\244nder",
	"Bread",
	"Brian Ford",
	"Caleb Makela",
	"Caliburn",
	"Cameron Meyer",
	"Carlos Rios",
	"Carl van der Geest",
	"Cerno_b",
	"Checkpoint Charlie",
	"chendrak",
	"Chris Cavalluzzi",
	"Chris Jagusch",
	"Chris Lee",
	"Christian Mauduit",
	"Christoph Czurda",
	"Christophe Gagnier",
	"Ciyvius",
	"Cody Parker",
	"Conall O",
	"Corchari",
	"Corey W",
	"cynwav",
	"Dakota Watkins",
	"Daniele Tolomelli",
	"Daniel Hoffmann",
	"Daniel Ramos",
	"Daren Scot Wilson",
	"Dave Jansen",
	"Davesnothere",
	"David Baker",
	"David B\303\264le",
	"David May",
	"David Maziarka",
	"Devin Carraway",
	"Devin R",
	"Dimitri Roche",
	"Donovan Hutcheon",
	"dragoon",
	"Ducky",
	"Duodecimal",
	"Edward Swartz",
	"Egon Elbre",
	"Elijah Anderson",
	"Emerson MX",
	"Ephemeral",
	"Eric Persson",
	"Eric Stokes",
	"Eric Williams",
	"Erkki Sepp\303\244l\303\244",
	"Ewan Holmes",
	"Felix Adam",
	"Fer DC",
	"Frank",
	"Frying\342\230\206Pan",
	"Game Endeavor",
	"Garrett Steffen",
	"Gary Thomas",
	"gebba",
	"Green Fox",
	"Greg Burkland",
	"Greyson Richey",
	"Grominet",
	"Guldoman",
	"Guo Hongci",
	"Hans Jorgensen",
	"Haplo",
	"Helge Maus",
	"Heribert Hirth",
	"Ian Richard Kunert",
	"Ian Williams",
	"itsybitesyspider",
	"iveks",
	"Jacob Wallace",
	"Jako Danar",
	"James Gary",
	"Jamie Massey",
	"JARKKO PARVIAINEN",
	"Jason Evans",
	"Jason Uechi",
	"Jeff Hungerford",
	"Jeffrey Berube",
	"Jennifer Graves",
	"Joakim Askenb\303\244ck",
	"Jo\303\243o Pedro Braz",
	"John Bruce",
	"Jonas",
	"Jonas Arndt",
	"Jonas Yamazaki",
	"Jonathan Bieber",
	"Jonathan Ellis",
	"Jon Sully",
	"Joseph Catrambone",
	"Josh Taylor",
	"Joshua Heidrich",
	"Juanfran",
	"Juan Maggi",
	"Juan Uys",
	"Jueast",
	"Julian le Roux",
	"Justin",
	"Justin Spedding",
	"Kalydi Bal\303\241zs",
	"Katsuomi Kobayashi",
	"Keedong Park",
	"Keegan Scott",
	"Keith Bradner",
	"Kent Jofur",
	"kindzadza",
	"Kodera Software",
	"KsyTek Games",
	"Kyle Burnett",
	"Kyle Jacobs",
	"Lasse le Dous",
	"Leland Vakarian",
	"Levi Berciu",
	"Linus Lind Lundgren",
	"Ludovic DELVAL",
	"Luigi Renna",
	"Luis Morao",
	"Lukas Komischke",
	"Luke Diasio",
	"Major Haul",
	"Malcolm",
	"Manuele Finocchiaro",
	"Mara Huldra",
	"Marcos Heitor Carvalho",
	"Markie Music",
	"Markus Michael Egger",
	"Markus Strompen",
	"Martin Holas",
	"Martin Li\305\241ka",
	"Martin Trbola",
	"Mat\304\233j Dr\303\241bek",
	"Mateo Navarrete",
	"Mathieu",
	"Matt Edwards",
	"Maverick",
	"Maxime Blade",
	"Maxwell",
	"McStuffings",
	"Melissa Mears",
	"Metal Demon 2000",
	"Michael Morrison",
	"Michal Skwarek",
	"Mikael Nordenberg",
	"Mikayla",
	"Mike Copley",
	"Mitchell J. Wagner",
	"Molly Jameson",
	"MoltenGears",
	"Moritz Weissenberger",
	"MrAZIE",
	"Mrjemandem",
	"naonya3",
	"Nathaniel",
	"neguse",
	"neighty",
	"Neil Blakey-Milner",
	"Neofytos Chimonas",
	"Nerdforge",
	"Nerdyninja",
	"Nick Eldrenkamp",
	"Nicolas Rosset",
	"Nik Rudenko",
	"Noel Billig",
	"Olexa Tourko",
	"oscar1000108",
	"Oscar Domingo",
	"ozrk",
	"Parth Patel",
	"Patrick Horn",
	"Patrick Inderm\303\274hle",
	"Patrickm",
	"Patrick Nafarrete",
	"Paul Black",
	"Paul Gieske",
	"Paul Mozet",
	"Pawe\305\202 \305\201yczkowski",
	"Pete",
	"Philip Ludington (MrPhil)",
	"Phoenix Jauregui",
	"Pierre Caye",
	"Pixel Archipel",
	"Point08",
	"Portponky",
	"PsycHead",
	"Puntigames",
	"Quincy Quincy",
	"Quinn Morrison",
	"Raghava Kovvali",
	"RagingRoosevelt",
	"Ragnar Pettersson",
	"Rammeow",
	"Rebecca H",
	"Richard Hayes",
	"Riley",
	"RobotCritter",
	"Rob Ruana",
	"Rodrigo Loli",
	"Roka",
	"Roland Rz\304\205sa",
	"Russ",
	"Ryan Groom",
	"Sammy Fischer",
	"Sebastian Michailidis",
	"Sekuta",
	"SeongWan Kim",
	"Sessamekesh",
	"SeungJong k",
	"Shane Lillie",
	"Shane Spoor",
	"Shaun Kohanowski",
	"simdee",
	"Simon Jonas Larsen",
	"Simon Schoenenberger",
	"Sina Yeganeh",
	"sirn",
	"Skalli",
	"slavfox",
	"smbe19",
	"smo1704",
	"SpicyCactuar",
	"Squidgy",
	"Squirrel",
	"Stephen Rice",
	"Stephen Schlie",
	"Sung soo Choi",
	"SxP",
	"tadashi endo",
	"Tarch",
	"TheVoiceInMyHead",
	"Thibaut DECROMBECQUE",
	"thomas",
	"Thomas Bechtold",
	"Thomas Pickett",
	"Tim Drumheller",
	"Tim Gleason",
	"Tim Klein",
	"Timothy B. MacDonald",
	"Tim Raveling",
	"Tim Riley",
	"Tom Webster",
	"Turgut Temucin",
	"Tyler Stafos",
	"Tyler Stepke",
	"Ukko K.",
	"Uther",
	"Vaughan Ling",
	"vgmoose",
	"Vincent Barkmann",
	"Vulinux",
	"Wapiti .",
	"wasitworthitdev",
	"Wiley Thompson",
	"William Bodin",
	"William Edwards",
	"Xatonym",
	"Yan Shi",
	"Zekim",
	"\343\202\261\343\203\253\343\203\231\343\203\255\343\202\271",
	"\350\262\264\345\256\217 \345\260\217\346\235\276",
	"And 241 anonymous donors",
	0
};
#endif // DONORS_GEN_H
